SOURCES = quine.ml

#Uncomment this, and remove -ppx ../ppx_blob below to use the installed version
#PACKS = ppx_blob

RESULT = quine

OCAMLNCFLAGS = -g -w -3 -ppx ../ppx_blob
OCAMLBCFLAGS = -g -w -3 -ppx ../ppx_blob
OCAMLLDFLAGS = -g

all : native-code

-include OCamlMakefile

