SOURCES = quine.ml

#Uncomment this, and remove -ppx ../ppx_netblob below to use the installed version
#PACKS = ppx_netblob

RESULT = quine

OCAMLNCFLAGS = -g -w -3 -ppx ../ppx_netblob
OCAMLBCFLAGS = -g -w -3 -ppx ../ppx_netblob
OCAMLLDFLAGS = -g

all : native-code

-include OCamlMakefile

